name: Release Version

on:
  release:
    types:
      - published

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare variables
        id: prepare
        shell: bash
        run: |
          REPO_SLUG="${GITHUB_REPOSITORY#*/}"
          OUT_DIR="${HOME}/${REPO_SLUG}"

          echo "OUT_DIR=$OUT_DIR" >> "$GITHUB_OUTPUT"
          echo "REPO_SLUG=$REPO_SLUG" >> "$GITHUB_OUTPUT"

      - name: Check Artifacts
        shell: bash
        run: |
          echo "${{ steps.prepare.outputs.REPO_SLUG }} ${{ github.ref_name }}"
          pwd
          echo "Current Directory"
          ls -lA
          cd $HOME
          echo "Home Directory"
          ls -lA
          cd ${{ steps.prepare.outputs.OUT_DIR }}
          echo "Output Directory"
          ls -lA

      - name: Download an artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.prepare.outputs.REPO_SLUG }}
