name: Test ENV

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Print
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref type: ${{ github.ref_type }}"

          npx dotenv-extra
          ls -la
          echo "# TEST" > .env
          npx dotenv-extra VAR $GITHUB_REF CTX ${{ github.ref }}
          cat .env
          echo ""

          node test.js
